### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by bmf7777** [nn-df/suricata-installation#2]
sudo -H bash suricata.sh 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

i get the following error ... sudo suricata-update -D /etc/suricata/ --no-merge in script 
any ideas what may be wrong? when i remove --no-merge the scripts finishes with no errors

8/11/2020 -- 16:17:36 - <Info> -- Enabled 0 rules.
8/11/2020 -- 16:17:36 - <Info> -- Modified 0 rules.
8/11/2020 -- 16:17:36 - <Info> -- Dropped 0 rules.
8/11/2020 -- 16:17:36 - <Info> -- Enabled 145 rules for flowbit dependencies.
8/11/2020 -- 16:17:36 - <Info> -- Creating directory /etc/suricata/rules.
8/11/2020 -- 16:17:36 - <Info> -- Backing up current rules.
Traceback (most recent call last):
  File "/usr/bin/suricata-update", line 33, in <module>
    sys.exit(main.main())
  File "/usr/bin/../lib/python3.8/site-packages/suricata/update/main.py", line 1299, in main
    sys.exit(_main())
  File "/usr/bin/../lib/python3.8/site-packages/suricata/update/main.py", line 1240, in _main
    config.get_output_dir(), os.path.basename(filename)))
  File "/usr/lib/python3.8/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not SourceFile

**Comment by nn-df** [comment]
Thanks. I will look into it.

**Comment by nn-df** [comment]
@bmf7777 already tested with current Ubuntu 20.04 just working fine. This issue maybe related to suricata-update package, i'm not sure.
For your information `--no-merge` command to store the rules not in single file, if you remove the command it will store the rules into a single file. I will close this issue.
References : https://suricata-update.readthedocs.io/en/latest/update.html
